FROM php:7.4-fpm
WORKDIR /var/www/html
COPY ./src/ .
EXPOSE 9000
CMD ["php-fpm"]
#CMD ["php", "api.php"]





#FROM php:7.4-fpm
#WORKDIR /var/www/html
#COPY ./src/ .

# Run the api.php script directly using PHP CLI
#CMD ["php", "api.php"]
